HParams:
  qtable: false          # Q-Table 사용여부
  episodes: 2001         # 에피소드 횟수(리플레이 횟수)

  eps_start: 0.9        # 초기 랜덤 행동 확률
  eps_end: 0.01         # 최종 랜덤 행동 확률
  eps_decay: 5000       # 랜덤 행동 확률 감소값

  alpha: 0.3            # 과거 기억 보존도
  gamma: 0.995            # 미래의 경로로부터의 영향도
  tau: 0.0005

  lr: 0.0001             # Learning Rate
  batch_size: 64        # Batch Size

  frame_skip: 4         # Frame skip
  frame_stack: 4        # Frame Stack
  ddqn_update_step: 1000 # Double DQN Update Steps
  update_freq: 4

Pinball:
  path: 'Game/'
  file_name: 'PINBALL.EXE'

Env:
  key_set: ['z', '/', 'space', 'x', '.']

Training:
  model_save_path: 'Pretrained/'
  
  resource_path: 'Resource/'
  ball_images: ['ball.bmp', 'ball_big.bmp', 'ball_middle.bmp', 'ball_max.bmp']
  dead_images: ['game_end.bmp']
  plunger_image: 'plunger_full.bmp'
  mask_image: 'mask.png'

  num_states: 8
  num_actions: 5

  save_eps: 100

  # x-range 300 ~ 330
  # y-range 30 ~ 380
  start_point: [300, 330, 30, 380]

  # x-range 70 ~ 250
  # y-range 300 ~ 410
  warn_point: [70, 250, 300, 410]

  # coordinate normalized
  max_x: 330
  max_y: 430
